package airprort_system;

import java.util.Date;

public class SystemReport {
    private String reportId;
    private Date generatedAt;
    private int totalUsers;
    private int totalFlights;
    private int totalBookings;
    private double totalRevenue;
    private String generatedByAdminId;

    public SystemReport() {
        this.generatedAt = new Date();
    }

    public SystemReport(String reportId, Date generatedAt, int totalUsers, int totalFlights,
                        int totalBookings, double totalRevenue, String generatedByAdminId) {
        this.reportId = reportId;
        this.generatedAt = generatedAt;
        this.totalUsers = totalUsers;
        this.totalFlights = totalFlights;
        this.totalBookings = totalBookings;
        this.totalRevenue = totalRevenue;
        this.generatedByAdminId = generatedByAdminId;
    }

    public String getReportId() {
        return reportId;
    }

    public Date getGeneratedAt() {
        return generatedAt;
    }

    public int getTotalUsers() {
        return totalUsers;
    }

    public int getTotalFlights() {
        return totalFlights;
    }

    public int getTotalBookings() {
        return totalBookings;
    }

    public double getTotalRevenue() {
        return totalRevenue;
    }

    public String getGeneratedByAdminId() {
        return generatedByAdminId;
    }

    @Override
    public String toString() {
        return "System Report\nGenerated At: " + generatedAt +
                "\nTotal Users: " + totalUsers +
                "\nTotal Flights: " + totalFlights +
                "\nTotal Bookings: " + totalBookings +
                "\nTotal Revenue: $" + totalRevenue +
                "\nGenerated by Admin ID: " + generatedByAdminId;
    }
}
